# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HTR United Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/HTR-United/htr-united-metadata-generator/archive/refs/heads/main.zip
    - name: Run Report
      env:
          ECHO-GITHUBWORKFLOW: "YES"
      run: |
        humGenerator --parse page --group **/*.xml --github-envs
        cat envs.txt >> $GITHUB_ENV
    - name: Create Awesome Badge
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "4347188370a0daf230c7acfbe6b17449"
        filename: "tapuscorpus_chars.json"
        label: "Transcribed Characters"
        message: ${{ env.HTRUNITED_CHARS }}
        color: informational
        style: "flat-square"
    - name: Create Awesome Badge for LINES
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "4347188370a0daf230c7acfbe6b17449"
        filename: "tapuscorpus_lines.json"
        label: "Transcribed Lines"
        message: ${{ env.HTRUNITED_LINES }}
        color: informational
        style: "flat-square"
    - name: Create Awesome Badge for REGIONS
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "4347188370a0daf230c7acfbe6b17449"
        filename: "tapuscorpus_regions.json"
        label: "Number of regions"
        message: ${{ env.HTRUNITED_REGNS }}
        color: informational
        style: "flat-square"
